# SPDX-License-Identifier: Apache-2.0
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ldapportal-frontend
  labels:
    app.kubernetes.io/name: ldapportal
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ldapportal
      app.kubernetes.io/component: frontend
