// SPDX-License-Identifier: Apache-2.0
package com.ldapportal.entity.enums;

/**
 * Indicates how an {@link com.ldapportal.entity.AuditEvent} was generated.
 */
public enum AuditSource {
    /** Generated by LDAPPortal when an admin performs a write via the REST API. */
    INTERNAL,
    /** Read from an LDAP directory's {@code cn=changelog} by the changelog poller. */
    LDAP_CHANGELOG
}
