-- Optional per-profile DN template for the admin new-user form.
--
-- NULL preserves the historical default: the entry DN is composed as
-- "rdnAttribute=rdnValue,targetUserDn". When set, the value is an
-- attribute-substitution expression (same engine as the attribute
-- computed-expressions, e.g. placing uid under ou=people) used to seed the
-- now-editable DN field on create. Any submitted DN is still validated
-- server-side to remain within the profile's target_user_dn subtree.
--
-- NOTE: keep this file free of dollar-sign and dollar-brace placeholder
-- tokens. Flyway runs placeholder substitution and dollar-quote parsing
-- across the whole script (comments included), so such a token makes Flyway
-- fail to parse the migration at startup.
ALTER TABLE provisioning_profiles ADD COLUMN dn_template VARCHAR(500);
