-- V1: Baseline schema — squashed from V1–V74 on 2026-05-27.
--
-- This file replaces the prior V1 + V2..V74 migration chain. Pre-baseline
-- migrations are archived under docs/migrations-archive/pre-baseline-2026-05/
-- for provenance. Going forward, new migrations are added at V75+ — never
-- edit or renumber this baseline (forward-only convention applies again).
--
-- Generated by `pg_dump --schema-only --no-owner --no-privileges
-- --no-comments` against a Postgres 16.13 DB with all 56 source migrations
-- (V1__baseline + V2..V74) applied in order. The psql-only \restrict /
-- \unrestrict directives that pg_dump emits have been stripped so Flyway
-- (which executes via JDBC) can run this file.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    username character varying(255) NOT NULL,
    display_name character varying(255),
    email character varying(255),
    role character varying(20) NOT NULL,
    auth_type character varying(10) DEFAULT 'LOCAL'::character varying NOT NULL,
    password_hash character varying(255),
    ldap_dn character varying(1000),
    active boolean DEFAULT true NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    theme_preference character varying(10) DEFAULT 'system'::character varying,
    oidc_id_token text,
    oidc_refresh_token_enc text,
    density_preference character varying(15) DEFAULT 'comfortable'::character varying,
    CONSTRAINT chk_account_auth_type CHECK (((auth_type)::text = ANY ((ARRAY['LOCAL'::character varying, 'LDAP'::character varying])::text[]))),
    CONSTRAINT chk_account_role CHECK (((role)::text = ANY ((ARRAY['SUPERADMIN'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT chk_auth_type CHECK (((auth_type)::text = ANY ((ARRAY['LOCAL'::character varying, 'LDAP'::character varying, 'OIDC'::character varying, 'WEBSEAL'::character varying])::text[])))
);


--
-- Name: admin_feature_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_feature_permissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    admin_account_id uuid NOT NULL,
    feature_key character varying(100) NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    profile_id uuid,
    CONSTRAINT chk_feature_key CHECK (((feature_key)::text = ANY ((ARRAY['user.create'::character varying, 'user.edit'::character varying, 'user.delete'::character varying, 'user.enable_disable'::character varying, 'user.move'::character varying, 'user.reset_password'::character varying, 'user.read'::character varying, 'group.edit'::character varying, 'group.manage_members'::character varying, 'group.create_delete'::character varying, 'group.read'::character varying, 'bulk.import'::character varying, 'bulk.export'::character varying, 'bulk.attribute_update'::character varying, 'reports.run'::character varying, 'reports.export'::character varying, 'reports.schedule'::character varying, 'playbook.manage'::character varying, 'playbook.execute'::character varying, 'approval.manage'::character varying, 'csv_template.manage'::character varying, 'directory.browse'::character varying, 'schema.read'::character varying])::text[])))
);


--
-- Name: admin_profile_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_profile_roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    admin_account_id uuid NOT NULL,
    profile_id uuid NOT NULL,
    base_role character varying(20) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: api_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    token_hash bytea NOT NULL,
    token_prefix character varying(32) NOT NULL,
    scopes jsonb,
    created_by_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    last_used_at timestamp with time zone,
    revoked_at timestamp with time zone,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_api_tokens_expiry_future CHECK ((expires_at > created_at)),
    CONSTRAINT chk_api_tokens_name_not_blank CHECK ((length(TRIM(BOTH FROM name)) > 0))
);


--
-- Name: application_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.application_settings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    app_name character varying(255) DEFAULT 'LDAP Portal'::character varying NOT NULL,
    logo_url character varying(1000),
    primary_colour character varying(20),
    secondary_colour character varying(20),
    session_timeout_minutes integer DEFAULT 60 NOT NULL,
    smtp_host character varying(255),
    smtp_port integer DEFAULT 587,
    smtp_sender_address character varying(255),
    smtp_username character varying(255),
    smtp_password_encrypted text,
    smtp_use_tls boolean DEFAULT true NOT NULL,
    s3_endpoint_url character varying(500),
    s3_bucket_name character varying(255),
    s3_access_key character varying(255),
    s3_secret_key_encrypted text,
    s3_region character varying(100),
    s3_presigned_url_ttl_hours integer DEFAULT 24 NOT NULL,
    ldap_auth_host character varying(255),
    ldap_auth_port integer,
    ldap_auth_ssl_mode character varying(10),
    ldap_auth_trust_all_certs boolean DEFAULT false NOT NULL,
    ldap_auth_trusted_cert_pem text,
    ldap_auth_bind_dn character varying(500),
    ldap_auth_bind_password_enc text,
    ldap_auth_user_search_base character varying(500),
    ldap_auth_bind_dn_pattern character varying(500),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    oidc_issuer_url character varying(1000),
    oidc_client_id character varying(500),
    oidc_client_secret_enc text,
    oidc_scopes character varying(500) DEFAULT 'openid profile email'::character varying,
    oidc_username_claim character varying(100) DEFAULT 'preferred_username'::character varying,
    superadmin_bypass_approval boolean DEFAULT false NOT NULL,
    siem_enabled boolean DEFAULT false NOT NULL,
    siem_protocol character varying(20),
    siem_host character varying(500),
    siem_port integer,
    siem_format character varying(20),
    siem_auth_token_enc text,
    webhook_url character varying(2000),
    webhook_auth_header_enc text,
    setup_completed boolean DEFAULT false NOT NULL,
    oidc_redirect_uri text,
    webseal_trusted_proxies text,
    webseal_user_header character varying(100) DEFAULT 'iv-user'::character varying,
    webseal_groups_header character varying(100) DEFAULT 'iv-groups'::character varying,
    webseal_logout_url character varying(500) DEFAULT '/pkmslogout'::character varying,
    directory_search_inline_edit_enabled boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_ldap_auth_ssl_mode CHECK (((ldap_auth_ssl_mode IS NULL) OR ((ldap_auth_ssl_mode)::text = ANY ((ARRAY['NONE'::character varying, 'LDAPS'::character varying, 'STARTTLS'::character varying])::text[]))))
);


--
-- Name: audit_data_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_data_sources (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    display_name character varying(255) NOT NULL,
    host character varying(255) NOT NULL,
    port integer DEFAULT 389 NOT NULL,
    ssl_mode character varying(10) DEFAULT 'NONE'::character varying NOT NULL,
    trust_all_certs boolean DEFAULT false NOT NULL,
    trusted_certificate_pem text,
    bind_dn character varying(1000) NOT NULL,
    bind_password_encrypted text NOT NULL,
    changelog_base_dn character varying(1000) DEFAULT 'cn=changelog'::character varying NOT NULL,
    branch_filter_dn character varying(1000),
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    changelog_format character varying(25) DEFAULT 'DSEE_CHANGELOG'::character varying NOT NULL,
    dirsync_cookie bytea,
    CONSTRAINT chk_audit_ssl_mode CHECK (((ssl_mode)::text = ANY ((ARRAY['NONE'::character varying, 'LDAPS'::character varying, 'STARTTLS'::character varying])::text[]))),
    CONSTRAINT chk_changelog_format CHECK (((changelog_format)::text = ANY ((ARRAY['DSEE_CHANGELOG'::character varying, 'OPENLDAP_ACCESSLOG'::character varying])::text[])))
);


--
-- Name: audit_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    source character varying(20) NOT NULL,
    actor_id uuid,
    actor_type character varying(20),
    actor_username character varying(255),
    directory_id uuid,
    directory_name character varying(255),
    action character varying(50) NOT NULL,
    target_dn character varying(2000),
    detail jsonb,
    changelog_change_number character varying(255),
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_audit_actor_type CHECK (((actor_type IS NULL) OR ((actor_type)::text = ANY ((ARRAY['ADMIN'::character varying, 'SUPERADMIN'::character varying])::text[])))),
    CONSTRAINT chk_audit_source CHECK (((source)::text = ANY ((ARRAY['INTERNAL'::character varying, 'LDAP_CHANGELOG'::character varying])::text[])))
);


--
-- Name: csv_mapping_template_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.csv_mapping_template_entries (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    template_id uuid NOT NULL,
    csv_column_name character varying(255) NOT NULL,
    csv_column_index integer,
    ldap_attribute character varying(255),
    ignored boolean DEFAULT false NOT NULL
);


--
-- Name: csv_mapping_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.csv_mapping_templates (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    target_key_attribute character varying(255) DEFAULT 'uid'::character varying NOT NULL,
    conflict_handling character varying(20) DEFAULT 'PROMPT'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    object_class character varying(255),
    skip_header_row boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_conflict_handling CHECK (((conflict_handling)::text = ANY ((ARRAY['PROMPT'::character varying, 'SKIP'::character varying, 'OVERWRITE'::character varying])::text[])))
);


--
-- Name: dashboard_layouts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dashboard_layouts (
    account_id uuid NOT NULL,
    layout jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: directory_connections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.directory_connections (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    display_name character varying(255) NOT NULL,
    host character varying(255) NOT NULL,
    port integer DEFAULT 389 NOT NULL,
    ssl_mode character varying(10) DEFAULT 'NONE'::character varying NOT NULL,
    trust_all_certs boolean DEFAULT false NOT NULL,
    trusted_certificate_pem text,
    bind_dn character varying(1000) NOT NULL,
    bind_password_encrypted text NOT NULL,
    base_dn character varying(1000) NOT NULL,
    paging_size integer DEFAULT 500 NOT NULL,
    pool_min_size integer DEFAULT 2 NOT NULL,
    pool_max_size integer DEFAULT 20 NOT NULL,
    pool_connect_timeout_seconds integer DEFAULT 10 NOT NULL,
    pool_response_timeout_seconds integer DEFAULT 30 NOT NULL,
    enable_disable_attribute character varying(255),
    enable_disable_value_type character varying(10) DEFAULT 'STRING'::character varying,
    enable_value character varying(500),
    disable_value character varying(500),
    audit_data_source_id uuid,
    enabled boolean DEFAULT true NOT NULL,
    is_user_repository boolean DEFAULT false NOT NULL,
    user_creation_base_dn character varying(1000),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    self_service_enabled boolean DEFAULT false NOT NULL,
    self_service_login_attribute character varying(64) DEFAULT 'uid'::character varying,
    directory_type character varying(20) DEFAULT 'GENERIC'::character varying NOT NULL,
    secondary_host character varying(255),
    secondary_port integer,
    global_catalog_port integer,
    tenant_id character varying(100),
    entra_client_id character varying(100),
    entra_client_secret_encrypted text,
    graph_endpoint character varying(255) DEFAULT 'https://graph.microsoft.com'::character varying,
    CONSTRAINT chk_dir_enable_disable_value_type CHECK (((enable_disable_value_type)::text = ANY ((ARRAY['BOOLEAN'::character varying, 'STRING'::character varying])::text[]))),
    CONSTRAINT chk_dir_ssl_mode CHECK (((ssl_mode)::text = ANY ((ARRAY['NONE'::character varying, 'LDAPS'::character varying, 'STARTTLS'::character varying])::text[])))
);


--
-- Name: directory_group_base_dns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.directory_group_base_dns (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    dn character varying(1000) NOT NULL,
    display_order integer DEFAULT 0 NOT NULL
);


--
-- Name: directory_user_base_dns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.directory_user_base_dns (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    dn character varying(1000) NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    editable boolean DEFAULT false NOT NULL
);


--
-- Name: dismissed_suggestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dismissed_suggestions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_id uuid NOT NULL,
    suggestion_key character varying(200) NOT NULL,
    dismissed_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: enabled_auth_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.enabled_auth_types (
    settings_id uuid NOT NULL,
    auth_type character varying(10) NOT NULL,
    CONSTRAINT chk_enabled_auth_type CHECK (((auth_type)::text = ANY ((ARRAY['LOCAL'::character varying, 'LDAP'::character varying, 'OIDC'::character varying, 'WEBSEAL'::character varying])::text[])))
);


--
-- Name: entra_group_memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entra_group_memberships (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    user_object_id character varying(100) NOT NULL,
    group_object_id character varying(100) NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: entra_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entra_groups (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    entra_object_id character varying(100) NOT NULL,
    display_name character varying(500),
    description text,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: entra_sync_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entra_sync_state (
    directory_id uuid NOT NULL,
    user_delta_token text,
    group_delta_token text,
    audit_last_poll timestamp with time zone,
    last_full_sync timestamp with time zone
);


--
-- Name: entra_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.entra_users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    entra_object_id character varying(100) NOT NULL,
    display_name character varying(500),
    user_principal_name character varying(500),
    mail character varying(500),
    department character varying(255),
    job_title character varying(255),
    employee_id character varying(255),
    account_enabled boolean,
    synced_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: event_outbox; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_outbox (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    subscription_id uuid NOT NULL,
    event_id uuid NOT NULL,
    event_type character varying(100) NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    envelope jsonb NOT NULL,
    status character varying(20) NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    next_attempt_at timestamp with time zone NOT NULL,
    last_error text,
    last_http_status integer,
    delivered_at timestamp with time zone,
    dead_lettered_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_event_outbox_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'DELIVERING'::character varying, 'DELIVERED'::character varying, 'DEAD_LETTERED'::character varying])::text[])))
);


--
-- Name: event_subscription; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_subscription (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(500),
    channel_type character varying(32) NOT NULL,
    destination_config jsonb NOT NULL,
    event_type_filter jsonb,
    enabled boolean DEFAULT true NOT NULL,
    created_by_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_event_subscription_name_not_blank CHECK ((length(TRIM(BOTH FROM name)) > 0))
);


--
-- Name: lifecycle_playbooks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lifecycle_playbooks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    profile_id uuid,
    name character varying(255) NOT NULL,
    description text,
    type character varying(20) NOT NULL,
    require_approval boolean DEFAULT false NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_playbook_type CHECK (((type)::text = ANY ((ARRAY['ONBOARD'::character varying, 'OFFBOARD'::character varying, 'CUSTOM'::character varying])::text[])))
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_id uuid NOT NULL,
    directory_id uuid,
    type character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    body text,
    link character varying(500),
    read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: oidc_pending_flows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.oidc_pending_flows (
    state text NOT NULL,
    nonce text NOT NULL,
    code_verifier text NOT NULL,
    redirect_uri text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: playbook_executions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.playbook_executions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    playbook_id uuid NOT NULL,
    target_dn character varying(500) NOT NULL,
    executed_by uuid,
    status character varying(20) NOT NULL,
    step_results jsonb DEFAULT '[]'::jsonb NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT chk_exec_status CHECK (((status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'PARTIAL'::character varying, 'FAILED'::character varying, 'ROLLED_BACK'::character varying])::text[])))
);


--
-- Name: playbook_steps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.playbook_steps (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    playbook_id uuid NOT NULL,
    step_order integer NOT NULL,
    action character varying(30) NOT NULL,
    parameters jsonb DEFAULT '{}'::jsonb NOT NULL,
    continue_on_error boolean DEFAULT false NOT NULL,
    CONSTRAINT chk_step_action CHECK (((action)::text = ANY ((ARRAY['ADD_TO_GROUP'::character varying, 'REMOVE_FROM_GROUP'::character varying, 'REMOVE_ALL_GROUPS'::character varying, 'SET_ATTRIBUTE'::character varying, 'REMOVE_ATTRIBUTE'::character varying, 'MOVE_OU'::character varying, 'DISABLE'::character varying, 'ENABLE'::character varying, 'DELETE'::character varying, 'NOTIFY'::character varying])::text[])))
);


--
-- Name: profile_additional_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_additional_profiles (
    profile_id uuid NOT NULL,
    additional_profile_id uuid NOT NULL,
    CONSTRAINT chk_no_self_ref CHECK ((profile_id <> additional_profile_id))
);


--
-- Name: profile_approval_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_approval_configs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    require_approval boolean DEFAULT false NOT NULL,
    approver_mode character varying(20) DEFAULT 'DATABASE'::character varying NOT NULL,
    approver_group_dn character varying(500),
    auto_escalate_days integer,
    escalation_account_id uuid
);


--
-- Name: profile_approvers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_approvers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    admin_account_id uuid NOT NULL
);


--
-- Name: profile_attribute_configs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_attribute_configs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    attribute_name character varying(100) NOT NULL,
    custom_label character varying(255),
    input_type character varying(20) DEFAULT 'TEXT'::character varying NOT NULL,
    required_on_create boolean DEFAULT false NOT NULL,
    editable_on_create boolean DEFAULT true NOT NULL,
    editable_on_update boolean DEFAULT true NOT NULL,
    self_service_edit boolean DEFAULT false NOT NULL,
    default_value character varying(500),
    computed_expression character varying(500),
    validation_regex character varying(500),
    validation_message character varying(255),
    allowed_values text,
    min_length integer,
    max_length integer,
    section_name character varying(100),
    column_span integer DEFAULT 6 NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    hidden boolean DEFAULT false NOT NULL,
    registration_section_name character varying(100),
    registration_column_span integer,
    registration_display_order integer,
    self_registration_edit boolean DEFAULT false NOT NULL,
    self_service_section_name character varying(100),
    self_service_column_span integer,
    self_service_display_order integer
);


--
-- Name: profile_group_assignments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_group_assignments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    group_dn character varying(500) NOT NULL,
    member_attribute character varying(50) DEFAULT 'member'::character varying NOT NULL,
    display_order integer DEFAULT 0 NOT NULL
);


--
-- Name: profile_lifecycle_policies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_lifecycle_policies (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    profile_id uuid NOT NULL,
    expires_after_days integer,
    max_renewals integer,
    renewal_days integer,
    on_expiry_action character varying(20) DEFAULT 'DISABLE'::character varying NOT NULL,
    on_expiry_move_dn character varying(500),
    on_expiry_remove_groups boolean DEFAULT true NOT NULL,
    on_expiry_notify boolean DEFAULT true NOT NULL,
    warning_days_before integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: profile_object_classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profile_object_classes (
    profile_id uuid NOT NULL,
    object_class_name character varying(255) NOT NULL
);


--
-- Name: provisioning_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.provisioning_profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    target_ou_dn character varying(500) NOT NULL,
    rdn_attribute character varying(100) NOT NULL,
    show_dn_field boolean DEFAULT true NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    self_registration_allowed boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    password_length integer DEFAULT 16 NOT NULL,
    password_uppercase boolean DEFAULT true NOT NULL,
    password_lowercase boolean DEFAULT true NOT NULL,
    password_digits boolean DEFAULT true NOT NULL,
    password_special boolean DEFAULT true NOT NULL,
    password_special_chars character varying(50) DEFAULT '!@#$%^&*'::character varying NOT NULL,
    email_password_to_user boolean DEFAULT false NOT NULL,
    auto_include_groups boolean DEFAULT false NOT NULL,
    exclude_auto_includes boolean DEFAULT false NOT NULL
);


--
-- Name: registration_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.registration_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    profile_id uuid NOT NULL,
    attributes jsonb NOT NULL,
    email character varying(255) NOT NULL,
    status character varying(30) DEFAULT 'PENDING_VERIFICATION'::character varying NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    verification_token character varying(255),
    verification_expires timestamp with time zone,
    justification text,
    pending_approval_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: scheduled_report_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scheduled_report_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    report_type character varying(50) NOT NULL,
    report_params jsonb,
    cron_expression character varying(100) NOT NULL,
    output_format character varying(10) DEFAULT 'CSV'::character varying NOT NULL,
    delivery_method character varying(10) DEFAULT 'EMAIL'::character varying NOT NULL,
    delivery_recipients text,
    s3_key_prefix character varying(500),
    enabled boolean DEFAULT true NOT NULL,
    last_run_at timestamp with time zone,
    last_run_status character varying(50),
    last_run_message text,
    created_by_admin_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_report_delivery_method CHECK (((delivery_method)::text = ANY ((ARRAY['EMAIL'::character varying, 'S3'::character varying])::text[]))),
    CONSTRAINT chk_report_output_format CHECK (((output_format)::text = ANY ((ARRAY['CSV'::character varying, 'PDF'::character varying])::text[]))),
    CONSTRAINT chk_report_type CHECK (((report_type)::text = ANY ((ARRAY['USERS_IN_GROUP'::character varying, 'USERS_IN_BRANCH'::character varying, 'USERS_WITH_NO_GROUP'::character varying, 'RECENTLY_ADDED'::character varying, 'RECENTLY_MODIFIED'::character varying, 'RECENTLY_DELETED'::character varying, 'DISABLED_ACCOUNTS'::character varying])::text[])))
);


--
-- Name: workflow_approvals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_approvals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    directory_id uuid NOT NULL,
    requested_by uuid NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    request_type character varying(30) NOT NULL,
    payload jsonb NOT NULL,
    reject_reason text,
    reviewed_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    reviewed_at timestamp with time zone,
    profile_id uuid,
    provision_error text,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_wa_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: admin_profile_roles admin_profile_roles_admin_account_id_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_profile_roles
    ADD CONSTRAINT admin_profile_roles_admin_account_id_profile_id_key UNIQUE (admin_account_id, profile_id);


--
-- Name: admin_profile_roles admin_profile_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_profile_roles
    ADD CONSTRAINT admin_profile_roles_pkey PRIMARY KEY (id);


--
-- Name: api_tokens api_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT api_tokens_pkey PRIMARY KEY (id);


--
-- Name: dashboard_layouts dashboard_layouts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dashboard_layouts
    ADD CONSTRAINT dashboard_layouts_pkey PRIMARY KEY (account_id);


--
-- Name: dismissed_suggestions dismissed_suggestions_account_id_suggestion_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dismissed_suggestions
    ADD CONSTRAINT dismissed_suggestions_account_id_suggestion_key_key UNIQUE (account_id, suggestion_key);


--
-- Name: dismissed_suggestions dismissed_suggestions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dismissed_suggestions
    ADD CONSTRAINT dismissed_suggestions_pkey PRIMARY KEY (id);


--
-- Name: enabled_auth_types enabled_auth_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enabled_auth_types
    ADD CONSTRAINT enabled_auth_types_pkey PRIMARY KEY (settings_id, auth_type);


--
-- Name: entra_group_memberships entra_group_memberships_directory_id_user_object_id_group_o_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_group_memberships
    ADD CONSTRAINT entra_group_memberships_directory_id_user_object_id_group_o_key UNIQUE (directory_id, user_object_id, group_object_id);


--
-- Name: entra_group_memberships entra_group_memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_group_memberships
    ADD CONSTRAINT entra_group_memberships_pkey PRIMARY KEY (id);


--
-- Name: entra_groups entra_groups_directory_id_entra_object_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_groups
    ADD CONSTRAINT entra_groups_directory_id_entra_object_id_key UNIQUE (directory_id, entra_object_id);


--
-- Name: entra_groups entra_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_groups
    ADD CONSTRAINT entra_groups_pkey PRIMARY KEY (id);


--
-- Name: entra_sync_state entra_sync_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_sync_state
    ADD CONSTRAINT entra_sync_state_pkey PRIMARY KEY (directory_id);


--
-- Name: entra_users entra_users_directory_id_entra_object_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_users
    ADD CONSTRAINT entra_users_directory_id_entra_object_id_key UNIQUE (directory_id, entra_object_id);


--
-- Name: entra_users entra_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_users
    ADD CONSTRAINT entra_users_pkey PRIMARY KEY (id);


--
-- Name: event_outbox event_outbox_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_outbox
    ADD CONSTRAINT event_outbox_pkey PRIMARY KEY (id);


--
-- Name: event_subscription event_subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_subscription
    ADD CONSTRAINT event_subscription_pkey PRIMARY KEY (id);


--
-- Name: lifecycle_playbooks lifecycle_playbooks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lifecycle_playbooks
    ADD CONSTRAINT lifecycle_playbooks_pkey PRIMARY KEY (id);


--
-- Name: oidc_pending_flows oidc_pending_flows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.oidc_pending_flows
    ADD CONSTRAINT oidc_pending_flows_pkey PRIMARY KEY (state);


--
-- Name: accounts pk_accounts; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT pk_accounts PRIMARY KEY (id);


--
-- Name: admin_feature_permissions pk_admin_feature_permissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_feature_permissions
    ADD CONSTRAINT pk_admin_feature_permissions PRIMARY KEY (id);


--
-- Name: application_settings pk_application_settings; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.application_settings
    ADD CONSTRAINT pk_application_settings PRIMARY KEY (id);


--
-- Name: audit_data_sources pk_audit_data_sources; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_data_sources
    ADD CONSTRAINT pk_audit_data_sources PRIMARY KEY (id);


--
-- Name: audit_events pk_audit_events; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT pk_audit_events PRIMARY KEY (id);


--
-- Name: csv_mapping_template_entries pk_csv_mapping_template_entries; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.csv_mapping_template_entries
    ADD CONSTRAINT pk_csv_mapping_template_entries PRIMARY KEY (id);


--
-- Name: csv_mapping_templates pk_csv_mapping_templates; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.csv_mapping_templates
    ADD CONSTRAINT pk_csv_mapping_templates PRIMARY KEY (id);


--
-- Name: directory_group_base_dns pk_dir_group_base_dns; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directory_group_base_dns
    ADD CONSTRAINT pk_dir_group_base_dns PRIMARY KEY (id);


--
-- Name: directory_user_base_dns pk_dir_user_base_dns; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directory_user_base_dns
    ADD CONSTRAINT pk_dir_user_base_dns PRIMARY KEY (id);


--
-- Name: directory_connections pk_directory_connections; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directory_connections
    ADD CONSTRAINT pk_directory_connections PRIMARY KEY (id);


--
-- Name: notifications pk_notifications; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT pk_notifications PRIMARY KEY (id);


--
-- Name: scheduled_report_jobs pk_scheduled_report_jobs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_jobs
    ADD CONSTRAINT pk_scheduled_report_jobs PRIMARY KEY (id);


--
-- Name: workflow_approvals pk_workflow_approvals; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_approvals
    ADD CONSTRAINT pk_workflow_approvals PRIMARY KEY (id);


--
-- Name: playbook_executions playbook_executions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playbook_executions
    ADD CONSTRAINT playbook_executions_pkey PRIMARY KEY (id);


--
-- Name: playbook_steps playbook_steps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playbook_steps
    ADD CONSTRAINT playbook_steps_pkey PRIMARY KEY (id);


--
-- Name: profile_additional_profiles profile_additional_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_additional_profiles
    ADD CONSTRAINT profile_additional_profiles_pkey PRIMARY KEY (profile_id, additional_profile_id);


--
-- Name: profile_approval_configs profile_approval_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_approval_configs
    ADD CONSTRAINT profile_approval_configs_pkey PRIMARY KEY (id);


--
-- Name: profile_approval_configs profile_approval_configs_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_approval_configs
    ADD CONSTRAINT profile_approval_configs_profile_id_key UNIQUE (profile_id);


--
-- Name: profile_approvers profile_approvers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_approvers
    ADD CONSTRAINT profile_approvers_pkey PRIMARY KEY (id);


--
-- Name: profile_approvers profile_approvers_profile_id_admin_account_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_approvers
    ADD CONSTRAINT profile_approvers_profile_id_admin_account_id_key UNIQUE (profile_id, admin_account_id);


--
-- Name: profile_attribute_configs profile_attribute_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_attribute_configs
    ADD CONSTRAINT profile_attribute_configs_pkey PRIMARY KEY (id);


--
-- Name: profile_attribute_configs profile_attribute_configs_profile_id_attribute_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_attribute_configs
    ADD CONSTRAINT profile_attribute_configs_profile_id_attribute_name_key UNIQUE (profile_id, attribute_name);


--
-- Name: profile_group_assignments profile_group_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_group_assignments
    ADD CONSTRAINT profile_group_assignments_pkey PRIMARY KEY (id);


--
-- Name: profile_group_assignments profile_group_assignments_profile_id_group_dn_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_group_assignments
    ADD CONSTRAINT profile_group_assignments_profile_id_group_dn_key UNIQUE (profile_id, group_dn);


--
-- Name: profile_lifecycle_policies profile_lifecycle_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_lifecycle_policies
    ADD CONSTRAINT profile_lifecycle_policies_pkey PRIMARY KEY (id);


--
-- Name: profile_lifecycle_policies profile_lifecycle_policies_profile_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_lifecycle_policies
    ADD CONSTRAINT profile_lifecycle_policies_profile_id_key UNIQUE (profile_id);


--
-- Name: provisioning_profiles provisioning_profiles_directory_id_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provisioning_profiles
    ADD CONSTRAINT provisioning_profiles_directory_id_name_key UNIQUE (directory_id, name);


--
-- Name: provisioning_profiles provisioning_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provisioning_profiles
    ADD CONSTRAINT provisioning_profiles_pkey PRIMARY KEY (id);


--
-- Name: registration_requests registration_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_requests
    ADD CONSTRAINT registration_requests_pkey PRIMARY KEY (id);


--
-- Name: accounts uq_account_username; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uq_account_username UNIQUE (username);


--
-- Name: csv_mapping_template_entries uq_csv_entry_template_col; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.csv_mapping_template_entries
    ADD CONSTRAINT uq_csv_entry_template_col UNIQUE (template_id, csv_column_name);


--
-- Name: csv_mapping_templates uq_csv_template_dir_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.csv_mapping_templates
    ADD CONSTRAINT uq_csv_template_dir_name UNIQUE (directory_id, name);


--
-- Name: lifecycle_playbooks uq_playbook_dir_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lifecycle_playbooks
    ADD CONSTRAINT uq_playbook_dir_name UNIQUE (directory_id, name);


--
-- Name: idx_accounts_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_accounts_active ON public.accounts USING btree (active);


--
-- Name: idx_accounts_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_accounts_role ON public.accounts USING btree (role);


--
-- Name: idx_afp_admin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_afp_admin ON public.admin_feature_permissions USING btree (admin_account_id);


--
-- Name: idx_afp_admin_profile; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_afp_admin_profile ON public.admin_feature_permissions USING btree (admin_account_id, profile_id);


--
-- Name: idx_api_tokens_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_tokens_created_by ON public.api_tokens USING btree (created_by_id);


--
-- Name: idx_api_tokens_expires_at_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_api_tokens_expires_at_active ON public.api_tokens USING btree (expires_at) WHERE (revoked_at IS NULL);


--
-- Name: idx_apr_admin_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_apr_admin_account ON public.admin_profile_roles USING btree (admin_account_id);


--
-- Name: idx_audit_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_action ON public.audit_events USING btree (action);


--
-- Name: idx_audit_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_actor ON public.audit_events USING btree (actor_id, occurred_at DESC);


--
-- Name: idx_audit_directory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_directory ON public.audit_events USING btree (directory_id, occurred_at DESC);


--
-- Name: idx_audit_occurred; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_occurred ON public.audit_events USING btree (occurred_at DESC);


--
-- Name: idx_audit_target_dn; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_target_dn ON public.audit_events USING btree (target_dn);


--
-- Name: idx_csv_entries_template; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_csv_entries_template ON public.csv_mapping_template_entries USING btree (template_id);


--
-- Name: idx_csv_templates_dir; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_csv_templates_dir ON public.csv_mapping_templates USING btree (directory_id);


--
-- Name: idx_dir_conn_enabled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dir_conn_enabled ON public.directory_connections USING btree (enabled);


--
-- Name: idx_entra_groups_dir; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entra_groups_dir ON public.entra_groups USING btree (directory_id);


--
-- Name: idx_entra_memberships_dir; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entra_memberships_dir ON public.entra_group_memberships USING btree (directory_id);


--
-- Name: idx_entra_memberships_group; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entra_memberships_group ON public.entra_group_memberships USING btree (directory_id, group_object_id);


--
-- Name: idx_entra_memberships_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entra_memberships_user ON public.entra_group_memberships USING btree (directory_id, user_object_id);


--
-- Name: idx_entra_users_dir; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_entra_users_dir ON public.entra_users USING btree (directory_id);


--
-- Name: idx_event_outbox_delivering; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_outbox_delivering ON public.event_outbox USING btree (next_attempt_at) WHERE ((status)::text = 'DELIVERING'::text);


--
-- Name: idx_event_outbox_dispatch; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_outbox_dispatch ON public.event_outbox USING btree (next_attempt_at) WHERE ((status)::text = 'PENDING'::text);


--
-- Name: idx_event_outbox_subscription_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_outbox_subscription_status ON public.event_outbox USING btree (subscription_id, status, created_at DESC);


--
-- Name: idx_event_subscription_enabled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_subscription_enabled ON public.event_subscription USING btree (enabled) WHERE (enabled = true);


--
-- Name: idx_exec_playbook; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exec_playbook ON public.playbook_executions USING btree (playbook_id);


--
-- Name: idx_group_base_dns_dir; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_group_base_dns_dir ON public.directory_group_base_dns USING btree (directory_id);


--
-- Name: idx_notifications_account_all; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_account_all ON public.notifications USING btree (account_id, created_at DESC);


--
-- Name: idx_notifications_account_unread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_account_unread ON public.notifications USING btree (account_id, created_at DESC) WHERE (NOT read);


--
-- Name: idx_oidc_pending_flows_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_oidc_pending_flows_created_at ON public.oidc_pending_flows USING btree (created_at);


--
-- Name: idx_playbook_dir; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_playbook_dir ON public.lifecycle_playbooks USING btree (directory_id);


--
-- Name: idx_registration_requests_directory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registration_requests_directory ON public.registration_requests USING btree (directory_id);


--
-- Name: idx_registration_requests_profile; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registration_requests_profile ON public.registration_requests USING btree (profile_id);


--
-- Name: idx_registration_requests_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registration_requests_status ON public.registration_requests USING btree (status);


--
-- Name: idx_registration_requests_token; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_registration_requests_token ON public.registration_requests USING btree (verification_token);


--
-- Name: idx_report_jobs_dir; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_report_jobs_dir ON public.scheduled_report_jobs USING btree (directory_id);


--
-- Name: idx_report_jobs_enabled; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_report_jobs_enabled ON public.scheduled_report_jobs USING btree (enabled);


--
-- Name: idx_user_base_dns_dir; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_base_dns_dir ON public.directory_user_base_dns USING btree (directory_id);


--
-- Name: uq_admin_feature_global; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_admin_feature_global ON public.admin_feature_permissions USING btree (admin_account_id, feature_key) WHERE (profile_id IS NULL);


--
-- Name: uq_admin_feature_per_profile; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_admin_feature_per_profile ON public.admin_feature_permissions USING btree (admin_account_id, profile_id, feature_key) WHERE (profile_id IS NOT NULL);


--
-- Name: uq_api_tokens_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_api_tokens_hash ON public.api_tokens USING btree (token_hash);


--
-- Name: admin_feature_permissions admin_feature_permissions_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_feature_permissions
    ADD CONSTRAINT admin_feature_permissions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: admin_profile_roles admin_profile_roles_admin_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_profile_roles
    ADD CONSTRAINT admin_profile_roles_admin_account_id_fkey FOREIGN KEY (admin_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: admin_profile_roles admin_profile_roles_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_profile_roles
    ADD CONSTRAINT admin_profile_roles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: api_tokens api_tokens_created_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_tokens
    ADD CONSTRAINT api_tokens_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: dashboard_layouts dashboard_layouts_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dashboard_layouts
    ADD CONSTRAINT dashboard_layouts_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: dismissed_suggestions dismissed_suggestions_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dismissed_suggestions
    ADD CONSTRAINT dismissed_suggestions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: enabled_auth_types enabled_auth_types_settings_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.enabled_auth_types
    ADD CONSTRAINT enabled_auth_types_settings_id_fkey FOREIGN KEY (settings_id) REFERENCES public.application_settings(id) ON DELETE CASCADE;


--
-- Name: entra_group_memberships entra_group_memberships_directory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_group_memberships
    ADD CONSTRAINT entra_group_memberships_directory_id_fkey FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: entra_groups entra_groups_directory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_groups
    ADD CONSTRAINT entra_groups_directory_id_fkey FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: entra_sync_state entra_sync_state_directory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_sync_state
    ADD CONSTRAINT entra_sync_state_directory_id_fkey FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: entra_users entra_users_directory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.entra_users
    ADD CONSTRAINT entra_users_directory_id_fkey FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: event_outbox event_outbox_subscription_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_outbox
    ADD CONSTRAINT event_outbox_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.event_subscription(id) ON DELETE CASCADE;


--
-- Name: event_subscription event_subscription_created_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_subscription
    ADD CONSTRAINT event_subscription_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES public.accounts(id) ON DELETE SET NULL;


--
-- Name: admin_feature_permissions fk_afp_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_feature_permissions
    ADD CONSTRAINT fk_afp_account FOREIGN KEY (admin_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: csv_mapping_template_entries fk_csv_entry_template; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.csv_mapping_template_entries
    ADD CONSTRAINT fk_csv_entry_template FOREIGN KEY (template_id) REFERENCES public.csv_mapping_templates(id) ON DELETE CASCADE;


--
-- Name: csv_mapping_templates fk_csv_template_directory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.csv_mapping_templates
    ADD CONSTRAINT fk_csv_template_directory FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: directory_connections fk_dir_conn_audit_source; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directory_connections
    ADD CONSTRAINT fk_dir_conn_audit_source FOREIGN KEY (audit_data_source_id) REFERENCES public.audit_data_sources(id) ON DELETE SET NULL;


--
-- Name: directory_group_base_dns fk_group_base_dns_dir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directory_group_base_dns
    ADD CONSTRAINT fk_group_base_dns_dir FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: notifications fk_notifications_account; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_notifications_account FOREIGN KEY (account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: scheduled_report_jobs fk_report_job_created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_jobs
    ADD CONSTRAINT fk_report_job_created_by FOREIGN KEY (created_by_admin_id) REFERENCES public.accounts(id) ON DELETE SET NULL;


--
-- Name: scheduled_report_jobs fk_report_job_directory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scheduled_report_jobs
    ADD CONSTRAINT fk_report_job_directory FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: directory_user_base_dns fk_user_base_dns_dir; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.directory_user_base_dns
    ADD CONSTRAINT fk_user_base_dns_dir FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: workflow_approvals fk_wa_directory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_approvals
    ADD CONSTRAINT fk_wa_directory FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: workflow_approvals fk_wa_profile; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_approvals
    ADD CONSTRAINT fk_wa_profile FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE SET NULL;


--
-- Name: workflow_approvals fk_wa_requester; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_approvals
    ADD CONSTRAINT fk_wa_requester FOREIGN KEY (requested_by) REFERENCES public.accounts(id);


--
-- Name: workflow_approvals fk_wa_reviewer; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_approvals
    ADD CONSTRAINT fk_wa_reviewer FOREIGN KEY (reviewed_by) REFERENCES public.accounts(id);


--
-- Name: lifecycle_playbooks lifecycle_playbooks_directory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lifecycle_playbooks
    ADD CONSTRAINT lifecycle_playbooks_directory_id_fkey FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: lifecycle_playbooks lifecycle_playbooks_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lifecycle_playbooks
    ADD CONSTRAINT lifecycle_playbooks_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE SET NULL;


--
-- Name: playbook_executions playbook_executions_executed_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playbook_executions
    ADD CONSTRAINT playbook_executions_executed_by_fkey FOREIGN KEY (executed_by) REFERENCES public.accounts(id);


--
-- Name: playbook_executions playbook_executions_playbook_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playbook_executions
    ADD CONSTRAINT playbook_executions_playbook_id_fkey FOREIGN KEY (playbook_id) REFERENCES public.lifecycle_playbooks(id) ON DELETE CASCADE;


--
-- Name: playbook_steps playbook_steps_playbook_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.playbook_steps
    ADD CONSTRAINT playbook_steps_playbook_id_fkey FOREIGN KEY (playbook_id) REFERENCES public.lifecycle_playbooks(id) ON DELETE CASCADE;


--
-- Name: profile_additional_profiles profile_additional_profiles_additional_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_additional_profiles
    ADD CONSTRAINT profile_additional_profiles_additional_profile_id_fkey FOREIGN KEY (additional_profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: profile_additional_profiles profile_additional_profiles_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_additional_profiles
    ADD CONSTRAINT profile_additional_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: profile_approval_configs profile_approval_configs_escalation_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_approval_configs
    ADD CONSTRAINT profile_approval_configs_escalation_account_id_fkey FOREIGN KEY (escalation_account_id) REFERENCES public.accounts(id);


--
-- Name: profile_approval_configs profile_approval_configs_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_approval_configs
    ADD CONSTRAINT profile_approval_configs_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: profile_approvers profile_approvers_admin_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_approvers
    ADD CONSTRAINT profile_approvers_admin_account_id_fkey FOREIGN KEY (admin_account_id) REFERENCES public.accounts(id) ON DELETE CASCADE;


--
-- Name: profile_approvers profile_approvers_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_approvers
    ADD CONSTRAINT profile_approvers_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: profile_attribute_configs profile_attribute_configs_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_attribute_configs
    ADD CONSTRAINT profile_attribute_configs_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: profile_group_assignments profile_group_assignments_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_group_assignments
    ADD CONSTRAINT profile_group_assignments_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: profile_lifecycle_policies profile_lifecycle_policies_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_lifecycle_policies
    ADD CONSTRAINT profile_lifecycle_policies_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: profile_object_classes profile_object_classes_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profile_object_classes
    ADD CONSTRAINT profile_object_classes_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- Name: provisioning_profiles provisioning_profiles_directory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.provisioning_profiles
    ADD CONSTRAINT provisioning_profiles_directory_id_fkey FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: registration_requests registration_requests_directory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_requests
    ADD CONSTRAINT registration_requests_directory_id_fkey FOREIGN KEY (directory_id) REFERENCES public.directory_connections(id) ON DELETE CASCADE;


--
-- Name: registration_requests registration_requests_pending_approval_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_requests
    ADD CONSTRAINT registration_requests_pending_approval_id_fkey FOREIGN KEY (pending_approval_id) REFERENCES public.workflow_approvals(id);


--
-- Name: registration_requests registration_requests_profile_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.registration_requests
    ADD CONSTRAINT registration_requests_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.provisioning_profiles(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


