#!/usr/bin/env bash
# Adds SPDX-License-Identifier headers to every .java file under core/ and ee/.
# Idempotent: skips files that already carry an SPDX-License-Identifier line.
#
# core/ -> Apache-2.0
# ee/   -> LicenseRef-LDAPPortal-Commercial
#
# Run from the repo root:  ./scripts/apply-spdx-headers.sh
#
# The license boundary mirrors docs/edition-boundary.md. Phase 5b extracts ee/
# into a separate private repo; until then SPDX headers are the per-file
# marker that keeps the Apache 2.0 / commercial line legible inside one tree.
set -euo pipefail

apply_header() {
  local root="$1"
  local spdx="$2"
  local count=0
  while IFS= read -r -d '' file; do
    if grep -q '^// SPDX-License-Identifier:' "$file"; then
      continue
    fi
    local tmp
    tmp="$(mktemp)"
    printf '// SPDX-License-Identifier: %s\n' "$spdx" > "$tmp"
    cat "$file" >> "$tmp"
    mv "$tmp" "$file"
    count=$((count + 1))
  done < <(find "$root" -type f -name '*.java' -print0)
  printf '%s: added header to %d files\n' "$root" "$count"
}

apply_header "core/src" "Apache-2.0"
apply_header "ee/src"   "LicenseRef-LDAPPortal-Commercial"

# Frontend (Vue 3). Same license boundary, different comment syntax:
#   .ts / .js -> // SPDX-License-Identifier: ...
#   .vue      -> <!-- SPDX-License-Identifier: ... --> (leading HTML comment,
#                outside the SFC blocks; the compiler ignores it)
# frontend/src/ee/ is the commercial subtree; everything else under
# frontend/src is Apache-2.0 (incl. src/ee-shim.js, the inert community stub).
apply_frontend_header() {
  local root="$1"
  local spdx="$2"
  local count=0
  while IFS= read -r -d '' file; do
    case "$file" in
      */api/openapi.d.ts) continue ;;  # generated by gen:api
    esac
    if grep -q 'SPDX-License-Identifier' "$file"; then
      continue
    fi
    local tmp
    tmp="$(mktemp)"
    case "$file" in
      *.vue) printf '<!-- SPDX-License-Identifier: %s -->\n' "$spdx" > "$tmp" ;;
      *)     printf '// SPDX-License-Identifier: %s\n' "$spdx" > "$tmp" ;;
    esac
    cat "$file" >> "$tmp"
    mv "$tmp" "$file"
    count=$((count + 1))
  done < <(find "$root" -type f \( -name '*.vue' -o -name '*.ts' -o -name '*.js' \) -print0)
  printf '%s: added header to %d files\n' "$root" "$count"
}

# ee subtree first so the idempotency guard skips it in the Apache-2.0 pass.
apply_frontend_header "frontend/src/ee" "LicenseRef-LDAPPortal-Commercial"
apply_frontend_header "frontend/src"    "Apache-2.0"
