#!/usr/bin/env bash
# Generate the minimum .env needed to start LDAP Portal with docker compose.
#
# Writes <repo-root>/.env with four values:
#   ENCRYPTION_KEY                 - AES-256 key   (openssl rand -base64 32)
#   JWT_SECRET                     - signing secret (openssl rand -base64 64)
#   BOOTSTRAP_SUPERADMIN_PASSWORD  - prompted (first superadmin login)
#   POSTGRES_PASSWORD              - prompted (database password)
#
# Everything else the app reads (POSTGRES_DB / POSTGRES_USER /
# BOOTSTRAP_SUPERADMIN_USERNAME / COOKIE_SECURE / ...) has a working default in
# compose.yaml, so it's intentionally omitted to keep this the minimum viable
# .env. Copy .env.example instead if you want the full set of tunables.
#
# Customer-safe: never overwrites an existing .env (pass --force to replace),
# writes the file mode 0600, and prints nothing secret to the terminal.
#
# Requires: openssl, bash. Run from anywhere — it writes to the repo root.
#   ./scripts/generate-env.sh
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"

die() { echo "ERROR: $*" >&2; exit 1; }
command -v openssl >/dev/null 2>&1 || die "openssl not found — needed to generate ENCRYPTION_KEY / JWT_SECRET."

FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1
if [ -e "$ENV_FILE" ] && [ "$FORCE" -ne 1 ]; then
  die ".env already exists at $ENV_FILE — refusing to overwrite. Re-run with --force to replace it."
fi

# Read a secret twice (hidden), require non-empty + matching, assign to $1.
prompt_secret() {
  local var="$1" label="$2" v1 v2
  while :; do
    read -r -s -p "$label: " v1; echo
    [ -n "$v1" ] || { echo "  (cannot be empty)"; continue; }
    read -r -s -p "$label (confirm): " v2; echo
    [ "$v1" = "$v2" ] || { echo "  (entries did not match — try again)"; continue; }
    printf -v "$var" '%s' "$v1"
    break
  done
}

echo "Generating the minimum .env for LDAP Portal at:"
echo "  $ENV_FILE"
echo

# openssl always appends a newline; `tr -d '\r\n'` strips it (and any CRLF on
# Windows / Git Bash) so no stray newline ends up embedded in the secret.
ENCRYPTION_KEY="$(openssl rand -base64 32 | tr -d '\r\n')"
JWT_SECRET="$(openssl rand -base64 64 | tr -d '\r\n')"

prompt_secret BOOTSTRAP_PW "Bootstrap superadmin password"
prompt_secret POSTGRES_PW  "Postgres password"

# Create the file with restrictive perms from the start.
umask 077
cat > "$ENV_FILE" <<EOF
# Minimum LDAP Portal environment — generated by scripts/generate-env.sh.
# Do NOT commit this file (it holds secrets; it is gitignored). See
# .env.example for the full, documented set of options.

# AES-256 key encrypting at-rest secrets (directory bind passwords, SMTP, ...).
# WARNING: changing this after first start makes existing encrypted data
# unreadable. Back it up; treat it like a master key.
ENCRYPTION_KEY=$ENCRYPTION_KEY

# JWT signing secret for session cookies / API tokens.
JWT_SECRET=$JWT_SECRET

# First superadmin login. This bootstrap account is only active until a
# permanent superadmin exists. Username defaults to 'superadmin'
# (set BOOTSTRAP_SUPERADMIN_USERNAME in compose to change it).
BOOTSTRAP_SUPERADMIN_PASSWORD=$BOOTSTRAP_PW

# PostgreSQL password — used by both the db container and the backend.
POSTGRES_PASSWORD=$POSTGRES_PW
EOF
chmod 600 "$ENV_FILE"

echo
echo "Wrote $ENV_FILE (mode 0600):"
echo "  ENCRYPTION_KEY, JWT_SECRET  (generated)"
echo "  BOOTSTRAP_SUPERADMIN_PASSWORD, POSTGRES_PASSWORD  (from your input)"
echo
echo "Start the stack with:  docker compose up -d   (or: make redeploy-fast)"
